name: devenv
description: "Setup development environment with devenv"
inputs:
  github-token:
    description: Provide a github token
    required: true
  cache-version:
    description: The version of the cache to use.
    required: false
    default: "v1"

runs:
  using: composite
  steps:
    - name: cache eget
      uses: actions/cache@v4
      with:
        path: ./.eget/bin
        key: ${{ runner.os }}-eget-${{ inputs.cache-version }}-${{ github.job }}-${{ hashFiles('.eget/.eget.toml') }}
        restore-keys: |
          ${{ runner.os }}-eget-${{ inputs.cache-version }}-${{ github.job }}-

    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: setup nix environment
      run: |
        nix profile add --accept-flake-config nixpkgs#cachix
        cachix use devenv
        nix profile add nixpkgs#devenv
      shell: bash

    - name: install flutter sdk via fvm
      run: |
        fvm install
        fvm use --force
      shell: devenv shell -- bash -e {0}

    - name: install dependencies
      run: install:all
      shell: devenv shell -- bash -e {0}
