name: devenv
description: "Setup development environment with devenv"
inputs:
  github-token:
    description: Provide a github token
    required: true
  cache-version:
    description: The version of the cache to use.
    required: false
    default: "v1"

runs:
  using: composite
  steps:
    - name: cache pnpm node
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/.local/share/pnpm
        key: ${{ runner.os }}-pnpm-node-${{ inputs.cache-version }}-${{ hashFiles('pnpm-workspace.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node-${{ inputs.cache-version }}-

    - name: install nix
      uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: setup nix environment
      run: |
        nix profile add --accept-flake-config nixpkgs#cachix
        cachix use devenv
        nix profile add nixpkgs#devenv
      shell: bash

    - name: install flutter sdk via fvm
      run: |
        devenv shell -- bash -e <<'EOF'
        fvm install
        fvm use --force
        EOF
      shell: bash

    - name: install dependencies
      run: |
        devenv shell -- bash -e <<'EOF'
        install:all
        EOF
      shell: bash
