import 'dart:typed_data';

import 'package:solana_kit_mobile_wallet_adapter_protocol/src/association_keypair.dart';
import 'package:solana_kit_mobile_wallet_adapter_protocol/src/crypto.dart';
import 'package:solana_kit_mobile_wallet_adapter_protocol/src/ecdh_keypair.dart';

/// Creates a HELLO_REQ message for the MWA handshake.
///
/// The HELLO_REQ consists of 129 bytes:
/// - Bytes 0-64: The ECDH public key in X9.62 uncompressed format (65 bytes)
/// - Bytes 65-128: ECDSA-SHA256 signature of the ECDH public key (64 bytes,
///   P1363 format: `r(32) || s(32)`)
///
/// The wallet uses the association keypair's public key (from the Intent URI)
/// to verify the signature, ensuring the ECDH key was generated by the same
/// party that initiated the association.
Uint8List createHelloReq(
  EcdhKeypair ecdhKeyPair,
  AssociationKeypair associationKeyPair,
) {
  final ecdhPublicKeyBytes = exportEcdhPublicKeyBytes(ecdhKeyPair);

  // Sign the ECDH public key with the association private key.
  final signatureBytes = ecdsaSign(
    ecdhPublicKeyBytes,
    associationKeyPair.privateKey,
  );

  // Concatenate: [ECDH pubkey (65)] [ECDSA signature (64)]
  final response = Uint8List(ecdhPublicKeyBytes.length + signatureBytes.length)
    ..setAll(0, ecdhPublicKeyBytes)
    ..setAll(ecdhPublicKeyBytes.length, signatureBytes);

  return response;
}
