import 'dart:typed_data';

import 'package:solana_kit_mpl_core/solana_kit_mpl_core.dart';
import 'package:test/test.dart';

void main() {
  test('generated byte fields have structural value equality', () {
    final first = HashedAssetSchema(
      assetHash: Uint8List.fromList(List<int>.filled(32, 1)),
      pluginHashes: [Uint8List.fromList(List<int>.filled(32, 2))],
    );
    final second = HashedAssetSchema(
      assetHash: Uint8List.fromList(List<int>.filled(32, 1)),
      pluginHashes: [Uint8List.fromList(List<int>.filled(32, 2))],
    );

    expect(first, second);
    expect(first.hashCode, second.hashCode);
  });
}
