name: solana_kit_examples
description: Runnable Dart examples for the Solana Kit SDK.
publish_to: none

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit: ^0.5.0
  solana_kit_accounts: ^0.5.0
  solana_kit_address_lookup_table: ^0.1.0
  solana_kit_addresses: ^0.5.0
  solana_kit_codecs: ^0.5.0
  solana_kit_codecs_core: ^0.5.0
  solana_kit_codecs_data_structures: ^0.5.0
  solana_kit_codecs_numbers: ^0.5.0
  solana_kit_codecs_strings: ^0.5.0
  solana_kit_config: ^0.1.0
  solana_kit_errors: ^0.5.0
  solana_kit_fast_stable_stringify: ^0.5.0
  solana_kit_helius: ^0.3.3
  solana_kit_instructions: ^0.5.0
  solana_kit_keys: ^0.5.0
  solana_kit_loader: ^0.1.0
  solana_kit_memo: ^0.1.0
  solana_kit_mpl_bubblegum: ^0.2.1
  solana_kit_offchain_messages: ^0.3.3
  solana_kit_options: ^0.5.0
  solana_kit_rpc: ^0.5.0
  solana_kit_rpc_api: ^0.5.0
  solana_kit_rpc_subscriptions: ^0.5.0
  solana_kit_rpc_subscriptions_channel_websocket: ^0.5.0
  solana_kit_rpc_types: ^0.5.0
  solana_kit_signers: ^0.5.0
  solana_kit_spl_account_compression: ^0.2.1
  solana_kit_stake: ^0.1.0
  solana_kit_sysvars: ^0.3.3
  solana_kit_transaction_confirmation: ^0.5.0
  solana_kit_transaction_messages: ^0.5.0
  solana_kit_transactions: ^0.5.0

dev_dependencies:
  solana_kit_lints: ^0.5.0
