import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:solana_kit_addresses/solana_kit_addresses.dart';
import 'package:solana_kit_errors/solana_kit_errors.dart';
import 'package:solana_kit_instructions/solana_kit_instructions.dart';
import 'package:solana_kit_keys/solana_kit_keys.dart';
import 'package:solana_kit_transaction_messages/solana_kit_transaction_messages.dart';
import 'package:solana_kit_transactions/solana_kit_transactions.dart';
import 'package:test/test.dart';

/// Resolves [relative] against this package's root, whether the test runner
/// starts in the package directory or in the workspace root.
File _fixture(String relative) {
  final current = Directory.current.path;
  final inPackage = current.endsWith('solana_kit_transactions');
  final base = inPackage
      ? current
      : '$current/packages/solana_kit_transactions';
  return File('$base/$relative'.replaceAll('//', '/'));
}

/// Regression tests for the version 1 transaction wire format.
///
/// Version 1 transactions (SIMD-0296 / SIMD-0385) raise the transaction size
/// ceiling from 1232 to 4096 bytes, move the signatures to the tail of the
/// envelope without a length prefix, and relocate the compute budget into a
/// fixed-offset message config. These tests pin the exact bytes against vectors
/// generated by `@solana/kit` running under Node, so a regression in the
/// envelope, config mask, or config value encoding fails loudly instead of
/// silently producing transactions the cluster rejects.
///
/// The vectors live in `test/fixtures/v1_wire_vectors.json`, which records the
/// upstream package version and the deterministic payer key. See
/// `test/fixtures/README.md` for the generator program.
void main() {
  final fixture = jsonDecode(
    _fixture('test/fixtures/v1_wire_vectors.json').readAsStringSync(),
  ) as Map<String, Object?>;
  final cases = fixture['cases']! as Map<String, Object?>;

  // The same 32-byte private key the fixture generator used. Deriving the
  // address here rather than reading it from the fixture also proves the port
  // agrees with upstream on key derivation.
  final payerKeyPair = createKeyPairFromPrivateKeyBytes(
    Uint8List.fromList(List.generate(32, (i) => i + 1)),
  );
  final payerAddress = getAddressFromPublicKey(payerKeyPair.publicKey);

  const memoProgramAddress = Address(
    'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr',
  );
  const destination = Address('So11111111111111111111111111111111111111112');
  const mockBlockhash = '11111111111111111111111111111111';

  /// Returns the wire vector recorded under [name].
  String vectorFor(String name) =>
      (cases[name]! as Map<String, Object?>)['wire']! as String;

  /// Builds a v1 message carrying a `dataLength`-byte memo payload.
  ///
  /// The instruction account order matches the fixture generator: destination
  /// first, then the payer as a signer.
  TransactionMessage buildV1Message({
    required int dataLength,
    V1TransactionConfig? config,
  }) {
    final instruction = Instruction(
      programAddress: memoProgramAddress,
      accounts: [
        const AccountMeta(address: destination, role: AccountRole.writable),
        AccountMeta(address: payerAddress, role: AccountRole.writableSigner),
      ],
      data: Uint8List(dataLength)..fillRange(0, dataLength, 7),
    );

    var message = createTransactionMessage(version: TransactionVersion.v1);
    message = setTransactionMessageFeePayer(payerAddress, message);
    message = setTransactionMessageLifetimeUsingBlockhash(
      BlockhashLifetimeConstraint(
        blockhash: mockBlockhash,
        lastValidBlockHeight: BigInt.from(1000),
      ),
      message,
    );
    message = appendTransactionMessageInstruction(instruction, message);
    message = fillTransactionMessageProvisoryResourceLimits(message);

    if (config != null) {
      message = setTransactionMessageConfig(config, message);
    }
    return message;
  }

  /// A v1 message with a fee payer but no instructions, for config assertions.
  TransactionMessage configOnlyMessage() {
    var message = createTransactionMessage(version: TransactionVersion.v1);
    message = setTransactionMessageFeePayer(payerAddress, message);
    message = setTransactionMessageLifetimeUsingBlockhash(
      BlockhashLifetimeConstraint(
        blockhash: mockBlockhash,
        lastValidBlockHeight: BigInt.from(1000),
      ),
      message,
    );
    return message;
  }

  /// Signs [message] with the deterministic payer and returns the base64 wire
  /// form.
  Future<String> signToWire(TransactionMessage message) async {
    final signed = await signTransaction(
      [payerKeyPair],
      compileTransaction(message),
    );
    return getBase64EncodedWireTransaction(signed);
  }

  /// Decodes [wire] back into a decompiled transaction message.
  TransactionMessage roundTrip(String wire) {
    final decoded = getTransactionDecoder().read(base64Decode(wire), 0).$1;
    return decompileTransactionMessage(
      getCompiledTransactionMessageDecoder()
          .read(
            decoded.messageBytes,
            0,
          )
          .$1,
    );
  }

  group('fixture', () {
    test('was generated from the payer this suite derives', () {
      expect(
        payerAddress.value,
        equals(fixture['feePayerAddress']),
      );
    });

    test('records the upstream package it came from', () {
      expect(fixture['upstreamPackage'], equals('@solana/kit'));
      expect(fixture['upstreamVersion'], isNotEmpty);
    });
  });

  group('v1 wire format matches upstream', () {
    test('produces the exact upstream bytes for a small transaction', () async {
      final wire = await signToWire(buildV1Message(dataLength: 200));

      expect(wire, equals(vectorFor('small')));
    });

    test(
      'produces the exact upstream bytes for a 3216-byte transaction',
      () async {
        final wire = await signToWire(buildV1Message(dataLength: 3000));

        expect(wire, equals(vectorFor('large')));
        // The whole point of v1: this does not fit in a legacy transaction.
        expect(
          base64Decode(wire).length,
          greaterThan(legacyTransactionSizeLimit),
        );
        expect(
          base64Decode(wire).length,
          equals((cases['large']! as Map<String, Object?>)['wireBytes']),
        );
      },
    );

    test(
      'produces the exact upstream bytes for a configured transaction',
      () async {
        final wire = await signToWire(
          buildV1Message(
            dataLength: 32,
            config: const V1TransactionConfig(
              computeUnitLimit: 250000,
              loadedAccountsDataSizeLimit: 65536,
            ),
          ),
        );

        expect(wire, equals(vectorFor('configured')));
      },
    );

    test('emits the 0x81 version discriminator at byte zero', () {
      final compiled = compileTransactionMessage(buildV1Message(dataLength: 8));
      final bytes = getCompiledTransactionMessageEncoder().encode(compiled);

      // 0x81 is the versioned-message flag (0x80) OR'd with version 1.
      expect(bytes.first, equals(0x81));
    });

    test('places the message before the signatures', () async {
      final signed = await signTransaction(
        [payerKeyPair],
        compileTransaction(buildV1Message(dataLength: 8)),
      );
      final bytes = getTransactionEncoder().encode(signed);

      // Byte 0 is the version; byte 1 is the header's signer count. A
      // signatures-first envelope would instead begin with a short-u16 count.
      expect(bytes[0], equals(0x81));
      expect(bytes[1], equals(1));
    });
  });

  group('v1 config encoding', () {
    test('omits config values when the mask is empty', () {
      final compiled = compileTransactionMessage(configOnlyMessage());

      expect(compiled.configMask, equals(0));
      expect(compiled.configValues, isEmpty);
    });

    test('sets the compute unit limit and loaded accounts bits', () {
      final message = setTransactionMessageComputeUnitLimit(
        250000,
        setTransactionMessageLoadedAccountsDataSizeLimit(
          65536,
          configOnlyMessage(),
        ),
      );

      // 0x4 is the compute unit limit bit, 0x8 the loaded accounts data bit.
      expect(compileTransactionMessage(message).configMask, equals(0xc));
    });

    test('encodes the priority fee as a u64 config value', () {
      final message = setTransactionMessageConfig(
        V1TransactionConfig(priorityFeeLamports: BigInt.from(5000)),
        configOnlyMessage(),
      );
      final compiled = compileTransactionMessage(message);

      expect(compiled.configMask, equals(0x3));
      expect(compiled.configValues, hasLength(1));
      expect(compiled.configValues!.single.kind, equals('u64'));
      expect(compiled.configValues!.single.value, equals(BigInt.from(5000)));
    });

    test('round-trips every config field through the message codec', () {
      final message = setTransactionMessageConfig(
        V1TransactionConfig(
          computeUnitLimit: 250000,
          heapSize: 131072,
          loadedAccountsDataSizeLimit: 65536,
          priorityFeeLamports: BigInt.from(5000),
        ),
        configOnlyMessage(),
      );

      final encoded = getCompiledTransactionMessageEncoder().encode(
        compileTransactionMessage(message),
      );
      final decompiled = decompileTransactionMessage(
        getCompiledTransactionMessageDecoder().decode(encoded),
      );

      expect(decompiled.config?.computeUnitLimit, equals(250000));
      expect(decompiled.config?.heapSize, equals(131072));
      expect(decompiled.config?.loadedAccountsDataSizeLimit, equals(65536));
      expect(decompiled.config?.priorityFeeLamports, equals(BigInt.from(5000)));
    });

    test('rejects compute unit limits above the runtime maximum', () {
      expect(
        () => setTransactionMessageComputeUnitLimit(
          1_400_001,
          configOnlyMessage(),
        ),
        throwsA(
          isA<SolanaError>().having(
            (e) => e.code,
            'code',
            SolanaErrorCode.transactionComputeUnitLimitOutOfRange,
          ),
        ),
      );
    });
  });

  group('v1 size limits', () {
    test('accepts a transaction far larger than the legacy limit', () {
      final transaction = compileTransaction(buildV1Message(dataLength: 3000));

      expect(
        getTransactionSize(transaction),
        greaterThan(legacyTransactionSizeLimit),
      );
      expect(
        getTransactionSize(transaction),
        lessThanOrEqualTo(v1TransactionSizeLimit),
      );
      expect(isTransactionWithinSizeLimit(transaction), isTrue);
    });

    test('rejects a v1 transaction above the 4096-byte ceiling', () {
      final transaction = compileTransaction(buildV1Message(dataLength: 4500));

      expect(
        getTransactionSize(transaction),
        greaterThan(v1TransactionSizeLimit),
      );
      expect(isTransactionWithinSizeLimit(transaction), isFalse);
      expect(
        () => assertIsTransactionWithinSizeLimit(transaction),
        throwsA(
          isA<SolanaError>().having(
            (e) => e.code,
            'code',
            SolanaErrorCode.transactionExceedsSizeLimit,
          ),
        ),
      );
    });

    test('the same payload does not fit in a v0 transaction', () {
      // The identical instruction set built as v0 exceeds 1232 bytes while the
      // v1 form of it fits, which is the reason v1 exists.
      var v0Message = createTransactionMessage(version: TransactionVersion.v0);
      v0Message = setTransactionMessageFeePayer(payerAddress, v0Message);
      v0Message = setTransactionMessageLifetimeUsingBlockhash(
        BlockhashLifetimeConstraint(
          blockhash: mockBlockhash,
          lastValidBlockHeight: BigInt.from(1000),
        ),
        v0Message,
      );
      v0Message = appendTransactionMessageInstruction(
        Instruction(
          programAddress: memoProgramAddress,
          accounts: [
            const AccountMeta(address: destination, role: AccountRole.writable),
            AccountMeta(
              address: payerAddress,
              role: AccountRole.writableSigner,
            ),
          ],
          data: Uint8List(3000)..fillRange(0, 3000, 7),
        ),
        v0Message,
      );

      expect(isTransactionMessageWithinSizeLimit(v0Message), isFalse);
      expect(
        isTransactionMessageWithinSizeLimit(buildV1Message(dataLength: 3000)),
        isTrue,
      );
    });

    test('applies the larger limit only to version 1 messages', () {
      expect(
        getTransactionMessageSizeLimit(
          createTransactionMessage(version: TransactionVersion.legacy),
        ),
        equals(legacyTransactionSizeLimit),
      );
      expect(
        getTransactionMessageSizeLimit(
          createTransactionMessage(version: TransactionVersion.v0),
        ),
        equals(legacyTransactionSizeLimit),
      );
      expect(
        getTransactionMessageSizeLimit(
          createTransactionMessage(version: TransactionVersion.v1),
        ),
        equals(v1TransactionSizeLimit),
      );
    });

    test('derives the 4096 limit from the compiled version byte', () {
      final transaction = compileTransaction(buildV1Message(dataLength: 2000));

      expect(getTransactionSizeLimit(transaction), equals(4096));
    });
  });

  group('v1 round-trip', () {
    test('preserves a large payload through encode and decode', () async {
      final wire = await signToWire(buildV1Message(dataLength: 3000));
      final decompiled = roundTrip(wire);

      expect(decompiled.version, equals(TransactionVersion.v1));
      expect(decompiled.instructions, hasLength(1));
      expect(decompiled.instructions.single.data, hasLength(3000));

      final decoded = getTransactionDecoder().read(base64Decode(wire), 0).$1;
      expect(getTransactionSizeLimit(decoded), equals(4096));
    });

    test('recovers the config values after a wire round-trip', () async {
      final wire = await signToWire(
        buildV1Message(
          dataLength: 32,
          config: const V1TransactionConfig(
            computeUnitLimit: 250000,
            loadedAccountsDataSizeLimit: 65536,
          ),
        ),
      );
      final decompiled = roundTrip(wire);

      expect(decompiled.config?.computeUnitLimit, equals(250000));
      expect(decompiled.config?.loadedAccountsDataSizeLimit, equals(65536));
    });

    test('recovers the fee payer signature from the tail block', () async {
      final signed = await signTransaction(
        [payerKeyPair],
        compileTransaction(buildV1Message(dataLength: 8)),
      );

      // A base58-encoded 64-byte signature is 87-88 characters.
      expect(
        getSignatureFromTransaction(signed).value.length,
        inInclusiveRange(86, 88),
      );
    });

    test(
      're-encoding a decoded transaction reproduces the same bytes',
      () async {
        final wire = base64Decode(
          await signToWire(buildV1Message(dataLength: 64)),
        );

        final decoded = getTransactionDecoder().read(wire, 0).$1;
        final reEncoded = getTransactionEncoder().encode(decoded);

        expect(reEncoded, equals(wire));
      },
    );
  });
}
